"""Smith per-k Toeplitz pack (Expert 2) — numpy column-HNF.

V_ij = U(h_i - h_j) becomes pack[s_i - s_j + off] in a small dense 3-D
Toeplitz array that fits workgroup shared memory (17–41 KB f16).
"""

from __future__ import annotations

import numpy as np


def _col_hnf(A: np.ndarray) -> np.ndarray:
    """Hermite normal form of integer matrix with shape (d, m), d<=3.

    Returns a full-rank (d, d) integer basis (columns generate the lattice).
    """
    A = np.array(A, dtype=np.int64, copy=True)
    d, m = A.shape
    # Column-style Euclidean reduction toward HNF (lower triangular, nonnegative).
    for i in range(d):
        # Clear row i using columns i..m-1
        while True:
            # Find pivot: nonzero entry in row i, cols i.. with min abs
            nz = [j for j in range(i, m) if A[i, j] != 0]
            if not nz:
                # insert a unit if possible from later rows — rare for full-rank lattices
                break
            j0 = min(nz, key=lambda j: abs(A[i, j]))
            if j0 != i:
                A[:, [i, j0]] = A[:, [j0, i]]
            # Make A[i,i] > 0
            if A[i, i] < 0:
                A[:, i] *= -1
            pivoted = False
            for j in range(i + 1, m):
                if A[i, j] == 0:
                    continue
                q = int(A[i, j] // A[i, i])
                A[:, j] -= q * A[:, i]
                if A[i, j] != 0:
                    # swap to continue Euclidean
                    A[:, [i, j]] = A[:, [j, i]]
                    pivoted = True
                    break
            if not pivoted:
                break
        # Reduce earlier columns against diagonal
        if A[i, i] == 0:
            continue
        if A[i, i] < 0:
            A[:, i] *= -1
        for j in range(i):
            if A[i, j] == 0:
                continue
            q = int(np.floor(A[i, j] / A[i, i]))
            A[:, j] -= q * A[:, i]
    # Keep first d columns; if rank-deficient, pad with zeros then fix
    B = A[:, :d].copy()
    # Ensure nonsingular: if det 0, fall back to identity (index-1 Z^3)
    if abs(int(round(np.linalg.det(B.astype(float))))) == 0:
        return np.eye(d, dtype=np.int64)
    return B


def delta_lattice_basis(H: np.ndarray) -> np.ndarray:
    """Integer basis (rows) of lattice generated by beam differences.

    Uses a local column-HNF of the nonzero beam-difference generators.
    """
    H = np.asarray(H, dtype=np.int64)
    diffs = (H[1:] - H[0]).T  # (3, n-1)
    keep = np.any(diffs != 0, axis=0)
    diffs = diffs[:, keep]
    if diffs.size == 0:
        return np.eye(3, dtype=np.int64)
    Hnf = _col_hnf(diffs)  # columns
    return Hnf.T  # rows


def lll_gram(A: np.ndarray, delta: float = 0.99, maxit: int = 2000) -> np.ndarray:
    """LLL-reduce Z^3 under inner product x^T A y. Returns unimodular U (rows short)."""
    B = np.eye(3, dtype=np.int64)

    def ip(x, y):
        return float(np.asarray(x, float) @ A @ np.asarray(y, float))

    def gso(B):
        Bs = np.zeros((3, 3))
        mu = np.zeros((3, 3))
        for i in range(3):
            Bs[i] = B[i].astype(float)
            for j in range(i):
                d = ip(Bs[j], Bs[j])
                mu[i, j] = ip(B[i].astype(float), Bs[j]) / d if d > 1e-300 else 0.0
                Bs[i] -= mu[i, j] * Bs[j]
        return Bs, mu

    k, it = 1, 0
    while k < 3 and it < maxit:
        it += 1
        Bs, mu = gso(B)
        for j in range(k - 1, -1, -1):
            q = int(round(mu[k, j]))
            if q:
                B[k] -= q * B[j]
                Bs, mu = gso(B)
        Bs, mu = gso(B)
        if ip(Bs[k], Bs[k]) >= (delta - mu[k, k - 1] ** 2) * ip(Bs[k - 1], Bs[k - 1]):
            k += 1
        else:
            B[[k, k - 1]] = B[[k - 1, k]]
            k = max(k - 1, 1)
    return B


def reduced_index_map(H: np.ndarray) -> np.ndarray:
    """M (3x3) mapping difference D=h_i-h_j to compact integer coords c = M D."""
    Bl = delta_lattice_basis(H)
    Bd = np.linalg.inv(Bl.astype(float)).T
    Hc = (H - H.mean(0)).astype(float)
    C = (Hc.T @ Hc) / max(len(Hc), 1) + 1e-9 * np.eye(3)
    U = lll_gram(Bd @ C @ Bd.T)
    return U.astype(float) @ Bd


def build_pack(
    H,
    tab,
    offset: int,
    pref: complex,
    stride_h: int,
    stride_k: int,
    *,
    sort_beams: bool = True,
):
    """Build per-k shared-memory Toeplitz pack.

    Returns (pack, s, off, order) with V_ij = pack[s_i - s_j + off] (diag zero separately).
    """
    H = np.asarray(H, dtype=np.int64)
    M = reduced_index_map(H)
    co = np.round(M @ (H - H[0]).T.astype(float)).T.astype(np.int64)
    lo, hi = co.min(0), co.max(0)
    ext = hi - lo + 1
    dext = 2 * ext - 1
    st = np.array([dext[1] * dext[2], dext[2], 1], dtype=np.int64)
    s = (co - lo) @ st
    off = int((ext - 1) @ st)

    order = np.argsort(s) if sort_beams else np.arange(len(s))
    s = s[order]

    Minv = np.linalg.inv(M)
    g = np.indices(tuple(dext.tolist())).reshape(3, -1).T - (ext - 1)
    dh = np.round(Minv @ g.T.astype(float)).T.astype(np.int64)
    dhash = dh[:, 0] * stride_h + dh[:, 1] * stride_k + dh[:, 2] + offset
    pack = np.zeros(int(np.prod(dext)), dtype=np.complex128)
    ok = (dhash >= 0) & (dhash < len(tab))
    pack[ok] = complex(pref) * np.asarray(tab)[dhash[ok]]
    return pack, s.astype(np.int32), off, order, dext


def matvec_V(pack, s, off, x):
    """y = V x with V_ij = pack[s_i-s_j+off], diag 0."""
    s64 = s.astype(np.int64)
    idx = s64[:, None] - s64[None, :] + off
    Vloc = pack[idx]
    np.fill_diagonal(Vloc, 0.0)
    return Vloc @ np.asarray(x, dtype=np.complex128)


def reconstruct_V(pack, s, off):
    s64 = s.astype(np.int64)
    idx = s64[:, None] - s64[None, :] + off
    V = pack[idx].copy()
    np.fill_diagonal(V, 0.0)
    return V
